# basic options
title: Basic Visual Blog
author: Bonnie Cooper
email: smilodon138@gmail.com
description: basic visual - basic neuroscience - basic data science - basic bonnie
github_username:  SmilodonCub

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

# for more options see https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
