# basic options
title: Basic Visual Blog
author: Bonnie Cooper
email: smilodon138@gmail.com
description: basic visual - basic neuroscience - basic data science - basic bonnie
github_username:  SmilodonCub

# Build settings
markdown: kramdown
theme: minima

# Display post-excerpts on the Home Page
show_excerpts: true

#add social media
minima:
  social_links:
    github: SmilodonCub
    facebook: smilodoncub
    instagram: gremlindoge
    linkedin: bonnie-cooper-ph-d
